### PR TITLE
more trade pattern

### PR DESCRIPTION
**Pull request by bulgit**

### CODE REVIEW

**Review by Erisa — CHANGES_REQUESTED** [review]
A lot of these lines
```
I will give a knife
I'm done with CSGO
I leave cs: go
I leave csgo
``` 

Are quite vague and have a much higher chance of false positives than the other ones I've put in. If you look at the first few lines, I usually put in more of the sentence to guarentee it's this pattern rather than just someone happening to leave CSGO.

What were the source messages for these texts? Perhaps we can take bigger portions out of tthem.

I really like the ` .ru/trade/?partner` though, that is useful.

**Comment by bulgit** [comment]
> A lot of these lines
> 
> ```
> I will give a knife
> I'm done with CSGO
> I leave cs: go
> I leave csgo
> ```
> 
> Are quite vague and have a much higher chance of false positives than the other ones I've put in. If you look at the first few lines, I usually put in more of the sentence to guarentee it's this pattern rather than just someone happening to leave CSGO.
> 
> What were the source messages for these texts? Perhaps we can take bigger portions out of tthem.
> 
> I really like the ` .ru/trade/?partner` though, that is useful.

Here are 2 messages found in another server:

> @everyone Hello ! I leave cs: go and give all my inventory, the first three who send a trade - I will give a knife
[link-removed]/trаdeoffer/=13721617&token=egAwWq88

> @everyone Hello! I'm done with CSGO and give all my inventory, the first three who send a trade - I will give a knife ;)   [link-removed]/trade/?partner=127332&token=28332

I'm not sure about "I will give a knife", would it be relevant in the community? I agree about others (I leave csgo)
Maybe: "I leave cs: go and give all my inventory" and "I'm done with CSGO and give all my inventory" would be better

**Comment by Erisa** [comment]
For the knife one, something like `trade - I will give a knife` would be simple but effective.

I agree with the others, both `"I leave cs: go and give all my inventory` and `I'm done with CSGO and give all my inventory` seem perfect.

**Comment by Erisa** [comment]
Also as a quick note, the caps sensitivity of these strings isn't considered by the bot, so I was trying to make them all lowercase in the file just as a point of making it standardrather than having mixed case.

Thank you for the contribution by the way!

**Comment by bulgit** [comment]
I think it should be ok, and the lowercase is better indeed

**Review by Erisa — APPROVED** [review]
Thanks!

**Pull request merged**
