### PR TITLE
shorten dehoisted 32char nicks *by* 1char, not *to* 1char

### PR DESCRIPTION
**Pull request by torchgm**
Someone thought that apparently this was a mistake, but in reality just screw people with long annoying nicknames, they deserve to be knocked down to one character. Eh, better fix it so people don't think its a "bug"

### CODE REVIEW

**Comment by Erisa** [comment]
Requested a rerun of the jobs because that doesnt look like your fault they failed

**Comment by torchgm** [comment]
> Requested a rerun of the jobs because that doesnt look like your fault they failed

i promise i didn't do anything bad :c

**Comment by Erisa** [comment]
Yeah the maintainers of D#+ are at fault:
```
#13 5.475 /app/MicrosoftBot.csproj : error NU3037: Package 'System.Security.Permissions 5.0.0' from source 'https://api.nuget.org/v3/index.json': The author primary signature validity period has expired. 
```

**Comment by torchgm** [comment]
oh that's rude of them

**Comment by Erisa** [comment]
Wait no thats Microsofts certificate, wat. 

Anyway I'll sort it out myself thanks.

**Comment by Erisa** [comment]
It builds locally, probably just a temporary hiccup on their end:
Screenshot_20210127-181108_Termux

**Pull request merged**
